version: "3"

services:
  client:
    build: ./client
    ports:
      - 80:8080
    volumes:
      - ./client:/app

  server:
    build: ./api
    restart: on-failure
    env_file: postgres.env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    networks:
      - db-tier
    ports:
      - 8080:80

  db:
    container_name: postgres
    image: postgres:13.1-alpine
    restart: on-failure
    env_file: ./postgres.env
    networks:
      - db-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./dashboard.sql:/docker-entrypoint-initdb.d/dashboard.sql
    ports:
      - 5432:5432

networks:
  db-tier: {}

volumes:
  db-data: {}
