version: "3"

services:
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    #image: node:latest
    #command: npm run docker
    #volumes:
    #  - ./client:/app
    #working_dir: /app
    #ports:
    #  - 80:3000

  server:
    build: ./api
    restart: on-failure
    env_file:
     - postgres.env
     - ./api/secret.env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    networks:
      - db-tier
    ports:
      - 8080:80

  db:
    container_name: postgres
    image: postgres:13.1-alpine
    restart: on-failure
    env_file: ./postgres.env
    networks:
      - db-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./dashboard.sql:/docker-entrypoint-initdb.d/dashboard.sql
    ports:
      - 5432:5432

networks:
  db-tier: {}

volumes:
  db-data: {}
