version: "3"

services:
  desktop:
    build: ./desktop
    environment:
      VUE_APP_API_HOST: 0.0.0.0
      VUE_APP_API_PORT: 8080
    ports:
      - 3000:8080
    volumes:
      - ./desktop:/app

  server:
    build: ./api
    restart: on-failure
    depends_on:
      - db
    env_file:
      - ./database/postgres.env
      - ./api/secret.env
    environment:
      - POSTGRES_HOST=area-postgres
      - POSTGRES_PORT=5432
    networks:
      - area-db-tier
    ports:
      - 8080:80

  db:
    container_name: area-postgres
    image: postgres:13.1-alpine
    restart: on-failure
    env_file:
      - ./database/postgres.env
    networks:
      - area-db-tier
    volumes:
      - area-db-data:/var/lib/postgresql/data
      - ./database/sql:/src
      - ./database/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - 5432:5432

networks:
  area-db-tier: {}

volumes:
  area-db-data: {}
