INSERT INTO public."Widgets" ("Id", "Name", "Description", "RequiresAuth", "ServiceId") VALUES (1, 'Imgur public gallery', 'See Imgur''s most recent posts', false, 1);
INSERT INTO public."Widgets" ("Id", "Name", "Description", "RequiresAuth", "ServiceId") VALUES (2, 'Imgur favorites', 'See your favorite posts from Imgur', true, 1);
INSERT INTO public."Widgets" ("Id", "Name", "Description", "RequiresAuth", "ServiceId") VALUES (3, 'Imgur uploads', 'See your posts on Imgur', true, 1);
INSERT INTO public."Widgets" ("Id", "Name", "Description", "RequiresAuth", "ServiceId") VALUES (4, 'Lorem Picsum random Image', 'An inspiring image every time you load the widget', false, 2);
INSERT INTO public."Widgets" ("Id", "Name", "Description", "RequiresAuth", "ServiceId") VALUES (5, 'Imgur gallery search', 'Search for images on Imgur', false, 1);
INSERT INTO public."Widgets" ("Id", "Name", "Description", "RequiresAuth", "ServiceId") VALUES (6, 'Spotify favorite artists', 'Get a list of your favorite artists on Spotify', true, 3);
INSERT INTO public."Widgets" ("Id", "Name", "Description", "RequiresAuth", "ServiceId") VALUES (7, 'Spotify favorite tracks', 'Get a list of your favorite tracks', true, 3);
INSERT INTO public."Widgets" ("Id", "Name", "Description", "RequiresAuth", "ServiceId") VALUES (8, 'Spotify history', 'Get a list of your recently played tracks', true, 3);
INSERT INTO public."Widgets" ("Id", "Name", "Description", "RequiresAuth", "ServiceId") VALUES (9, 'Top headlines', 'See the most recent top headlines', false, 4);
INSERT INTO public."Widgets" ("Id", "Name", "Description", "RequiresAuth", "ServiceId") VALUES (10, 'News search', 'Search for headlines from the past month', false, 4);
INSERT INTO public."Widgets" ("Id", "Name", "Description", "RequiresAuth", "ServiceId") VALUES (11, 'Random cat images', 'See a bunch of cat images', false, 5);
INSERT INTO public."Widgets" ("Id", "Name", "Description", "RequiresAuth", "ServiceId") VALUES (12, 'Random dad joke', 'Get a random dad joke', false, 6);