INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (1, 1, 'Newest', 'Newest');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (1, 5, 'Oldest', 'Oldest');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (2, 6, 'Viral', 'Viral');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (2, 7, 'Time', 'Time');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (2, 8, 'Top', 'Top');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (2, 9, 'Rising', 'Rising');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (3, 10, 'Hot', 'Hot');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (3, 11, 'Top', 'Top');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (3, 12, 'User', 'User');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 13, 'AZ', 'Azerbaijani');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 14, 'BG', 'Bulgarian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 15, 'BN', 'Bengali');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 16, 'BR', 'Portuguese (Brazil)');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 17, 'BS', 'Bosnian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 18, 'CA', 'Catalan');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 19, 'CS', 'Czech');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 20, 'CY', 'Welsh');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 21, 'DA', 'Danish');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 22, 'DE', 'German');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 23, 'EL', 'Greek');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 24, 'EN', 'English');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 25, 'EO', 'Esperanto');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 26, 'ES', 'Spanish');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 27, 'ET', 'Estonian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 28, 'EU', 'Basque');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 29, 'FA', 'Farsi');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 30, 'ID', 'Indonesian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 31, 'FI', 'Finnish');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 32, 'FR', 'French');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 33, 'GL', 'Galician');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 34, 'HE', 'Hebrew');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 35, 'HI', 'Hindi');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 36, 'HR', 'Croatian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 37, 'HT', 'Haitian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 38, 'HU', 'Hungarian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 39, 'HY', 'Armenian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 40, 'LV', 'Latvian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 41, 'IS', 'Icelandic');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 42, 'IT', 'Italian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 44, 'JV', 'Javanese');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 45, 'KK', 'Kazakh');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 46, 'KO', 'Korean');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 48, 'LB', 'Arabic');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 49, 'LT', 'Lithuanian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 50, 'PL', 'Polish');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 51, 'MG', 'Madagasikara');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 52, 'MK', 'Macedonian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 53, 'ML', 'Malayalam');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 54, 'MR', 'Marathi');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 55, 'MS', 'Malaysian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 56, 'NL', 'Dutch');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 57, 'NN', 'Norwegian (Nynorsk)');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 58, 'NO', 'Norwegian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 59, 'OC', 'Occitan');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 60, 'SW', 'Swahili');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 61, 'PT', 'Portuguese (Portugal)');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 62, 'RO', 'Romanian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 63, 'RU', 'Russian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 64, 'SH', 'Serbo-Croatian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 65, 'SK', 'Slovak');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 66, 'SL', 'Slovenian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 67, 'SQ', 'Albanian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 68, 'SR', 'Serbian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 69, 'SV', 'Swedish');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 70, 'ZH', 'Chinese');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 71, 'TA', 'Tamil');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 72, 'TE', 'Telugu');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 73, 'TH', 'Thai');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 74, 'TL', 'Tagalog');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 75, 'TR', 'Turkish');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 76, 'UK', 'Ukrainian');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 77, 'UR', 'Urdu');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 78, 'VI', 'Vietnamese');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 80, 'AF', 'Afrikaans');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 81, 'AN', 'Aragonese');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (4, 82, 'AR', 'Arabic');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (5, 83, 'Business', 'Business');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (5, 84, 'Entertainment', 'Entertainment');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (5, 85, 'Health', 'Health');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (5, 86, 'Science', 'Science');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (5, 87, 'Sports', 'Sports');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (5, 88, 'Technology', 'Technology');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 89, 'AE', 'United Arab Emirates');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 90, 'AR', 'Argentina');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 91, 'AT', 'Austria');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 92, 'AU', 'Australia');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 93, 'BE', 'Belgium');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 94, 'BG', 'Bulgaria');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 95, 'BR', 'Brazil');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 96, 'CA', 'Canada');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 97, 'CH', 'Switzerland');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 98, 'CN', 'China');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 99, 'CO', 'Colombia');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 100, 'CU', 'Cuba');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 101, 'CZ', 'Czechia');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 102, 'DE', 'Germany');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 103, 'EG', 'Egypt');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 104, 'FR', 'France');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 105, 'GB', 'United Kingdom');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 106, 'GR', 'Greece');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 107, 'HK', 'Hong Kong');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 108, 'HU', 'Hungary');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 109, 'ID', 'Indonesia');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 110, 'IE', 'Ireland');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 111, 'IL', 'Israel');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 112, 'IN', 'India');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 113, 'IT', 'Italy');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 114, 'JP', 'Japan');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 115, 'KR', 'Korea');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 116, 'LT', 'Lithuania');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 117, 'LV', 'Latvia');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 118, 'MA', 'Morocco');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 119, 'MX', 'Mexico');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 120, 'MY', 'Malaysia');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 121, 'NG', 'Nigeria');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 122, 'NL', 'Netherlands');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 123, 'NO', 'Norway');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 124, 'NZ', 'New Zealand');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 125, 'PH', 'Philippines');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 126, 'PL', 'Poland');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 127, 'PT', 'Portugal');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 128, 'RO', 'Romania');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 129, 'RS', 'Serbia');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 138, 'RU', 'Russia');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 130, 'SA', 'Saudi Arabia');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 131, 'SE', 'Sweden');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 132, 'SG', 'Singapore');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 133, 'SI', 'Slovenia');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 134, 'SK', 'Slovakia');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 135, 'TH', 'Thailand');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 136, 'TR', 'Turkey');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 137, 'TW', 'Taiwan');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 142, 'UA', 'Ukraine');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 139, 'US', 'United States');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 140, 'VE', 'Venezuela');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 141, 'ZA', 'South Africa');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (7, 143, 'longterm', 'Long term');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (7, 144, 'mediumterm', 'Medium term');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (7, 145, 'shortterm', 'Short term');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (5, 146, '_', 'Select a category');
INSERT INTO public."EnumHasValues" ("EnumModelId", "Id", "Value", "DisplayName") VALUES (6, 147, '_', 'Select a country');