create table "__EFMigrationsHistory"
(
    "MigrationId" varchar(150) not null
        constraint "PK___EFMigrationsHistory"
            primary key,
    "ProductVersion" varchar(32) not null
);

alter table "__EFMigrationsHistory" owner to postgres;

create table "Services"
(
    "Id" integer generated by default as identity
        constraint "PK_Services"
            primary key,
    "Name" text default ''::text not null
);

alter table "Services" owner to postgres;

create table "AspNetUsers"
(
    "Id" integer generated by default as identity
        constraint "PK_AspNetUsers"
            primary key,
    "UserName" varchar(256) default ''::text not null,
    "Email" varchar(256) default ''::text not null,
    "AccessFailedCount" integer default 0 not null,
    "ConcurrencyStamp" text,
    "EmailConfirmed" boolean default false not null,
    "LockoutEnabled" boolean default false not null,
    "LockoutEnd" timestamp with time zone,
    "NormalizedEmail" varchar(256),
    "NormalizedUserName" varchar(256),
    "PasswordHash" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean default false not null,
    "SecurityStamp" text,
    "TwoFactorEnabled" boolean default false not null
);

alter table "AspNetUsers" owner to postgres;

create index "EmailIndex"
    on "AspNetUsers" ("NormalizedEmail");

create unique index "UserNameIndex"
    on "AspNetUsers" ("NormalizedUserName");

create table "Widgets"
(
    "Id" integer generated by default as identity
        constraint "PK_Widgets"
            primary key,
    "Name" text default ''::text not null,
    "Description" text default ''::text not null,
    "RequiresAuth" boolean default false not null,
    "ServiceId" integer default 0 not null
        constraint "FK_Widgets_Services_ServiceId"
            references "Services"
                on delete cascade,
    "Frequency" integer default 0 not null
);

alter table "Widgets" owner to postgres;

create index "IX_Widgets_ServiceId"
    on "Widgets" ("ServiceId");

create table "UserHasServiceTokens"
(
    "UserModelId" integer not null
        constraint "FK_UserHasServiceTokens_AspNetUsers_UserModelId"
            references "AspNetUsers"
                on delete cascade,
    "Id" integer generated by default as identity,
    "Json" text default ''::text not null,
    "ServiceId" integer default 0 not null
        constraint "FK_UserHasServiceTokens_Services_ServiceId"
            references "Services"
                on delete cascade,
    constraint "PK_UserHasServiceTokens"
        primary key ("UserModelId", "Id")
);

alter table "UserHasServiceTokens" owner to postgres;

create index "IX_UserHasServiceTokens_ServiceId"
    on "UserHasServiceTokens" ("ServiceId");

create table "UsersToWidgets"
(
    "UserId" integer not null
        constraint "FK_UsersToWidgets_AspNetUsers_UserId"
            references "AspNetUsers"
                on delete cascade,
    "WidgetId" integer not null
        constraint "FK_UsersToWidgets_Widgets_WidgetId"
            references "Widgets"
                on delete cascade,
    constraint "PK_UsersToWidgets"
        primary key ("UserId", "WidgetId")
);

alter table "UsersToWidgets" owner to postgres;

create index "IX_UsersToWidgets_WidgetId"
    on "UsersToWidgets" ("WidgetId");

create table "Params"
(
    "Id" integer generated by default as identity
        constraint "PK_Params"
            primary key,
    "Name" text not null,
    "Type" integer not null,
    "Value" text,
    "Required" boolean not null,
    "WidgetId" integer not null
        constraint "FK_Params_Widgets_WidgetId"
            references "Widgets"
                on delete cascade
);

alter table "Params" owner to postgres;

create index "IX_Params_WidgetId"
    on "Params" ("WidgetId");

create table "UserHasParams"
(
    "UserModelId" integer not null
        constraint "FK_UserHasParams_AspNetUsers_UserModelId"
            references "AspNetUsers"
                on delete cascade,
    "Id" integer generated by default as identity,
    "ParamId" integer not null
        constraint "FK_UserHasParams_Params_ParamId"
            references "Params"
                on delete cascade,
    "Value" text not null,
    constraint "PK_UserHasParams"
        primary key ("UserModelId", "Id")
);

alter table "UserHasParams" owner to postgres;

create index "IX_UserHasParams_ParamId"
    on "UserHasParams" ("ParamId");

create table "AspNetRoles"
(
    "Id" integer generated by default as identity
        constraint "PK_AspNetRoles"
            primary key,
    "Name" varchar(256),
    "NormalizedName" varchar(256),
    "ConcurrencyStamp" text
);

alter table "AspNetRoles" owner to postgres;

create unique index "RoleNameIndex"
    on "AspNetRoles" ("NormalizedName");

create table "AspNetUserClaims"
(
    "Id" integer generated by default as identity
        constraint "PK_AspNetUserClaims"
            primary key,
    "UserId" integer not null
        constraint "FK_AspNetUserClaims_AspNetUsers_UserId"
            references "AspNetUsers"
                on delete cascade,
    "ClaimType" text,
    "ClaimValue" text
);

alter table "AspNetUserClaims" owner to postgres;

create index "IX_AspNetUserClaims_UserId"
    on "AspNetUserClaims" ("UserId");

create table "AspNetUserLogins"
(
    "LoginProvider" text not null,
    "ProviderKey" text not null,
    "ProviderDisplayName" text,
    "UserId" integer not null
        constraint "FK_AspNetUserLogins_AspNetUsers_UserId"
            references "AspNetUsers"
                on delete cascade,
    constraint "PK_AspNetUserLogins"
        primary key ("LoginProvider", "ProviderKey")
);

alter table "AspNetUserLogins" owner to postgres;

create index "IX_AspNetUserLogins_UserId"
    on "AspNetUserLogins" ("UserId");

create table "AspNetUserTokens"
(
    "UserId" integer not null
        constraint "FK_AspNetUserTokens_AspNetUsers_UserId"
            references "AspNetUsers"
                on delete cascade,
    "LoginProvider" text not null,
    "Name" text not null,
    "Value" text,
    constraint "PK_AspNetUserTokens"
        primary key ("UserId", "LoginProvider", "Name")
);

alter table "AspNetUserTokens" owner to postgres;

create table "AspNetRoleClaims"
(
    "Id" integer generated by default as identity
        constraint "PK_AspNetRoleClaims"
            primary key,
    "RoleId" integer not null
        constraint "FK_AspNetRoleClaims_AspNetRoles_RoleId"
            references "AspNetRoles"
                on delete cascade,
    "ClaimType" text,
    "ClaimValue" text
);

alter table "AspNetRoleClaims" owner to postgres;

create index "IX_AspNetRoleClaims_RoleId"
    on "AspNetRoleClaims" ("RoleId");

create table "AspNetUserRoles"
(
    "UserId" integer not null
        constraint "FK_AspNetUserRoles_AspNetUsers_UserId"
            references "AspNetUsers"
                on delete cascade,
    "RoleId" integer not null
        constraint "FK_AspNetUserRoles_AspNetRoles_RoleId"
            references "AspNetRoles"
                on delete cascade,
    constraint "PK_AspNetUserRoles"
        primary key ("UserId", "RoleId")
);

alter table "AspNetUserRoles" owner to postgres;

create index "IX_AspNetUserRoles_RoleId"
    on "AspNetUserRoles" ("RoleId");

create table "UserHasDevices"
(
    "Id" bigint not null
        constraint "PK_UserHasDevices"
            primary key,
    "UserId" integer not null,
    "FirstUsed" bigint not null,
    "LastUsed" bigint not null,
    "Country" text not null,
    "Device" integer not null,
    "Browser" integer not null,
    "BrowserVersion" text not null,
    "Os" integer not null,
    "OsVersion" text not null,
    "Architecture" integer not null,
    "UserModelId" integer not null
        constraint "FK_UserHasDevices_AspNetUsers_UserModelId"
            references "AspNetUsers"
                on delete cascade
);

alter table "UserHasDevices" owner to postgres;

create index "IX_UserHasDevices_UserModelId"
    on "UserHasDevices" ("UserModelId");

