name: ASP.NET build & test

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Start build docker services
      run: docker-compose build
    - name: Start docker
      run: docker-compose up -d
    - name: Restore dependencies
      working-directory: api/Area.AcceptanceTests
      run: dotnet restore
    - name: Build
      working-directory: api/Area.AcceptanceTests
      run: dotnet build --no-restore
    - name: Test
      working-directory: api/Area.AcceptanceTests
      run: dotnet test --no-build --verbosity normal
