name: Push to groups' repository

on: push

jobs:
  push-adrien-and-arthur:
    name: Push to Adrien and Arthurs' repository
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: |
            ${{ secrets.SSH_KEY_DEPLOY_ADRIEN }}
      - uses: actions/checkout@v2
      - shell: bash
        run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - shell: bash
        run: git remote add epitech git@github.com:EpitechIT2020/B-DEV-500-BDX-5-1-cardgames-arthur.lemeux.git
      - shell: bash
        run: git push epitech

  push-albert-and-mathias:
    name: Push to Mathias and Albert's repository
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: |
            ${{ secrets.SSH_KEY_DEPLOY_ALBERT }}
      - uses: actions/checkout@v2
      - shell: bash
        run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - shell: bash
        run: git remote add epitech git@github.com:EpitechIT2020/B-DEV-500-BDX-5-1-cardgames-albert.corson.git
      - shell: bash
        run: git push epitech
