name: Push to Epitech's repository

on: push

jobs:
  push-to-epitech:
    name: Push to Epitech's group repository
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        id: extract_branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: |
            ${{ secrets.SSH_DEPLOY_KEY }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}
          fetch-depth: '0'
      - shell: bash
        run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - shell: bash
        run: git remote add epitech git@github.com:EpitechIT2020/B-YEP-500-BDX-5-1-area-albert.corson.git
      - shell: bash
        run: git push --force epitech
